module cnetmod.orm.semantic_schema_migration;
import std;
import cnetmod.utils.sha256;

namespace cnetmod::orm {
namespace {
    auto identifier(std::string_view s, relational_dialect d) -> std::expected<std::string, schema_render_error>
    {
        if (s.empty() || !std::ranges::all_of(s, [](unsigned char c)
                             {
                                 return std::isalnum(c) || c == '_';
                             }))
            return std::unexpected(schema_render_error{"schema identifier must contain only letters, digits, and underscores"});
        return std::format("{}{}{}", d == relational_dialect::mysql ? '`' : '\"', s, d == relational_dialect::mysql ? '`' : '\"');
    }

    auto type(const column_definition& c, relational_dialect d) -> std::expected<std::string, schema_render_error>
    {
        switch (c.type)
        {
        case relational_column_type::boolean:
            return d == relational_dialect::mysql ? "BOOLEAN" : "BOOLEAN";
        case relational_column_type::int32:
            return "INTEGER";
        case relational_column_type::int64:
            return "BIGINT";
        case relational_column_type::decimal:
            return "DECIMAL";
        case relational_column_type::varchar:
            if (!c.length || !*c.length)
                return std::unexpected(schema_render_error{"varchar requires a positive length"});
            return std::format("VARCHAR({})", *c.length);
        case relational_column_type::text:
            return "TEXT";
        case relational_column_type::uuid:
            return d == relational_dialect::mysql ? "CHAR(36)" : "UUID";
        case relational_column_type::timestamp:
            return d == relational_dialect::mysql ? "DATETIME(6)" : "TIMESTAMPTZ";
        case relational_column_type::json:
            return d == relational_dialect::mysql ? "JSON" : "JSONB";
        case relational_column_type::binary:
            return d == relational_dialect::mysql ? "LONGBLOB" : "BYTEA";
        }
        std::unreachable();
    }

    auto column(const column_definition& c, relational_dialect d) -> std::expected<std::string, schema_render_error>
    {
        auto n = identifier(c.name, d);
        auto t = type(c, d);
        if (!n)
            return std::unexpected(n.error());
        if (!t)
            return std::unexpected(t.error());
        std::string o = *n + " " + *t;
        if (c.auto_generated)
            o += d == relational_dialect::mysql ? " AUTO_INCREMENT" : " GENERATED BY DEFAULT AS IDENTITY";
        if (!c.nullable || c.primary_key)
            o += " NOT NULL";
        if (c.default_value)
        {
            auto literal = std::visit([](const auto& value) -> std::string
                {
                    using value_type = std::decay_t<decltype(value)>;
                    if constexpr (std::same_as<value_type, current_timestamp_default>)
                        return "CURRENT_TIMESTAMP";
                    else if constexpr (std::same_as<value_type, schema_literal>)
                        return std::visit([](const auto& nested) -> std::string
                            {
                                using nested_type = std::decay_t<decltype(nested)>;
                                if constexpr (std::same_as<nested_type, bool>)
                                    return nested ? "TRUE" : "FALSE";
                                else if constexpr (std::same_as<nested_type, std::int64_t>)
                                    return std::to_string(nested);
                                else
                                {
                                    std::string escaped;
                                    escaped.reserve(nested.size());
                                    for (char ch : nested)
                                    {
                                        if (ch == '\'')
                                            escaped += "''";
                                        else
                                            escaped += ch;
                                    }
                                    return "'" + escaped + "'";
                                }
                            },
                            value);
                },
                *c.default_value);
            o += " DEFAULT " + literal;
        }
        return o;
    }

    auto list(const std::vector<std::string>& xs, relational_dialect d) -> std::expected<std::string, schema_render_error>
    {
        if (xs.empty())
            return std::unexpected(schema_render_error{"constraint requires columns"});
        std::string o;
        for (auto& x : xs)
        {
            auto q = identifier(x, d);
            if (!q)
                return std::unexpected(q.error());
            if (!o.empty())
                o += ",";
            o += *q;
        }
        return o;
    }

    auto join(const std::vector<std::string>& xs)
    {
        std::string o;
        for (auto& x : xs)
        {
            if (!o.empty())
                o += ",";
            o += x;
        }
        return o;
    }

    auto action(referential_action value) -> std::string_view
    {
        switch (value)
        {
        case referential_action::restrict_:
            return "RESTRICT";
        case referential_action::cascade:
            return "CASCADE";
        case referential_action::set_null:
            return "SET NULL";
        case referential_action::no_action:
            return "NO ACTION";
        }
        std::unreachable();
    }

    auto comparison(check_comparison value) -> std::string_view
    {
        switch (value)
        {
        case check_comparison::equal:
            return "=";
        case check_comparison::not_equal:
            return "<>";
        case check_comparison::less:
            return "<";
        case check_comparison::less_equal:
            return "<=";
        case check_comparison::greater:
            return ">";
        case check_comparison::greater_equal:
            return ">=";
        }
        std::unreachable();
    }

    auto literal(const schema_literal& value) -> std::string
    {
        return std::visit([](const auto& nested) -> std::string
            {
                using value_type = std::decay_t<decltype(nested)>;
                if constexpr (std::same_as<value_type, bool>)
                    return nested ? "TRUE" : "FALSE";
                else if constexpr (std::same_as<value_type, std::int64_t>)
                    return std::to_string(nested);
                else
                {
                    std::string escaped;
                    for (char ch : nested)
                    {
                        if (ch == '\'')
                            escaped += "''";
                        else
                            escaped += ch;
                    }
                    return "'" + escaped + "'";
                }
            },
            value);
    }

    auto predicate(const check_predicate& value, relational_dialect dialect) -> std::expected<std::string, schema_render_error>
    {
        return std::visit([&](const auto& item) -> std::expected<std::string, schema_render_error>
            {
                using predicate_type = std::decay_t<decltype(item)>;
                if constexpr (std::same_as<predicate_type, column_literal_predicate>)
                {
                    auto name = identifier(item.column, dialect);
                    if (!name)
                        return std::unexpected(name.error());
                    return *name + " " + std::string(comparison(item.comparison)) + " " + literal(item.value);
                }
                else if constexpr (std::same_as<predicate_type, column_set_predicate>)
                {
                    auto name = identifier(item.column, dialect);
                    if (!name)
                        return std::unexpected(name.error());
                    if (item.values.empty())
                        return std::unexpected(schema_render_error{"IN check requires at least one literal"});
                    std::string values;
                    for (const auto& value : item.values)
                    {
                        if (!values.empty())
                            values += ",";
                        values += literal(value);
                    }
                    return *name + " IN (" + values + ")";
                }
                else if constexpr (std::same_as<predicate_type, column_like_predicate>)
                {
                    auto name = identifier(item.column, dialect);
                    if (!name)
                        return std::unexpected(name.error());
                    return *name + " LIKE " + literal(schema_literal{item.pattern});
                }
                else
                {
                    auto left = identifier(item.left_column, dialect), right = identifier(item.right_column, dialect);
                    if (!left)
                        return std::unexpected(left.error());
                    if (!right)
                        return std::unexpected(right.error());
                    return *left + " " + std::string(comparison(item.comparison)) + " " + *right;
                }
            },
            value);
    }
} // namespace

auto semantic_version::valid() const noexcept -> bool
{
    return major || minor || patch;
}

auto semantic_version::to_string() const -> std::string
{
    return std::format("{}.{}.{}", major, minor, patch);
}

auto render_schema_migration(const schema_migration& m, relational_dialect d) -> std::expected<std::vector<std::string>, schema_render_error>
{
    if (!m.version.valid() || m.name.empty() || m.operations.empty())
        return std::unexpected(schema_render_error{"migration requires version, name, and operations"});
    std::vector<std::string> out;
    for (auto& op : m.operations)
    {
        auto r = std::visit([&](auto&& x) -> std::expected<std::string, schema_render_error>
            {
                using T = std::decay_t<decltype(x)>;
                if constexpr (std::same_as<T, create_table_operation>)
                {
                    auto t = identifier(x.table.name, d);
                    if (!t || x.table.columns.empty())
                        return std::unexpected(schema_render_error{"table requires a valid name and columns"});
                    std::vector<std::string> p;
                    std::vector<std::string> pk;
                    for (auto& c : x.table.columns)
                    {
                        auto q = column(c, d);
                        if (!q)
                            return std::unexpected(q.error());
                        p.push_back(*q);
                        if (c.primary_key)
                            pk.push_back(c.name);
                    }
                    if (!pk.empty())
                    {
                        auto q = list(pk, d);
                        if (!q)
                            return std::unexpected(q.error());
                        p.push_back("PRIMARY KEY (" + *q + ")");
                    }
                    return "CREATE TABLE " + *t + " (" + join(p) + ")";
                }
                else if constexpr (std::same_as<T, add_column_operation>)
                {
                    auto t = identifier(x.table, d);
                    auto c = column(x.column, d);
                    if (!t)
                        return std::unexpected(t.error());
                    if (!c)
                        return std::unexpected(c.error());
                    return "ALTER TABLE " + *t + " ADD COLUMN " + *c;
                }
                else if constexpr (std::same_as<T, add_index_operation>)
                {
                    auto n = identifier(x.index.name, d), t = identifier(x.table, d), c = list(x.index.columns, d);
                    if (!n)
                        return std::unexpected(n.error());
                    if (!t)
                        return std::unexpected(t.error());
                    if (!c)
                        return std::unexpected(c.error());
                    return std::string("CREATE ") + (x.index.unique ? "UNIQUE " : "") + "INDEX " + *n + " ON " + *t + " (" + *c + ")";
                }
                else if constexpr (std::same_as<T, add_unique_constraint_operation>)
                {
                    auto t = identifier(x.table, d), n = identifier(x.constraint.name, d), c = list(x.constraint.columns, d);
                    if (!t)
                        return std::unexpected(t.error());
                    if (!n)
                        return std::unexpected(n.error());
                    if (!c)
                        return std::unexpected(c.error());
                    return "ALTER TABLE " + *t + " ADD CONSTRAINT " + *n + " UNIQUE (" + *c + ")";
                }
                else if constexpr (std::same_as<T, add_foreign_key_operation>)
                {
                    auto t = identifier(x.table, d), n = identifier(x.constraint.name, d), c = list(x.constraint.columns, d), rt = identifier(x.constraint.referenced_table, d), rc = list(x.constraint.referenced_columns, d);
                    if (!t)
                        return std::unexpected(t.error());
                    if (!n)
                        return std::unexpected(n.error());
                    if (!c)
                        return std::unexpected(c.error());
                    if (!rt)
                        return std::unexpected(rt.error());
                    if (!rc || x.constraint.columns.size() != x.constraint.referenced_columns.size())
                        return std::unexpected(schema_render_error{"foreign key column counts must match"});
                    return "ALTER TABLE " + *t + " ADD CONSTRAINT " + *n + " FOREIGN KEY (" + *c + ") REFERENCES " + *rt + " (" + *rc + ") ON DELETE " + std::string(action(x.constraint.on_delete));
                }
                else
                {
                    auto t = identifier(x.table, d), n = identifier(x.constraint.name, d);
                    if (!t)
                        return std::unexpected(t.error());
                    if (!n)
                        return std::unexpected(schema_render_error{"check constraint requires a name"});
                    auto expression = predicate(x.constraint.predicate, d);
                    if (!expression)
                        return std::unexpected(expression.error());
                    return "ALTER TABLE " + *t + " ADD CONSTRAINT " + *n + " CHECK (" + *expression + ")";
                }
            },
            op);
        if (!r)
            return std::unexpected(r.error());
        out.push_back(std::move(*r));
        if (const auto* create = std::get_if<create_table_operation>(&op))
        {
            const auto append = [&](schema_operation nested) -> std::optional<schema_render_error>
            {
                auto rendered = render_schema_migration(schema_migration{.version = m.version, .name = m.name, .operations = {std::move(nested)}}, d);
                if (!rendered)
                    return rendered.error();
                out.insert(out.end(), std::make_move_iterator(rendered->begin()), std::make_move_iterator(rendered->end()));
                return std::nullopt;
            };
            for (const auto& index : create->table.indexes)
                if (auto error = append(add_index_operation{create->table.name, index}))
                    return std::unexpected(*error);
            for (const auto& constraint : create->table.unique_constraints)
                if (auto error = append(add_unique_constraint_operation{create->table.name, constraint}))
                    return std::unexpected(*error);
            for (const auto& constraint : create->table.foreign_keys)
                if (auto error = append(add_foreign_key_operation{create->table.name, constraint}))
                    return std::unexpected(*error);
            for (const auto& constraint : create->table.checks)
                if (auto error = append(add_check_constraint_operation{create->table.name, constraint}))
                    return std::unexpected(*error);
        }
    }
    return out;
}

auto schema_migration_checksum::to_hex() const -> std::string
{
    std::string text;
    text.reserve(bytes.size() * 2);
    for (const auto byte : bytes)
        text += std::format("{:02x}", std::to_integer<unsigned char>(byte));
    return text;
}

namespace {
    auto version_less(const semantic_version& left, const semantic_version& right) noexcept -> bool
    {
        return std::tie(left.major, left.minor, left.patch) < std::tie(right.major, right.minor, right.patch);
    }

    auto same_version(const semantic_version& left, const semantic_version& right) noexcept -> bool
    {
        return !version_less(left, right) && !version_less(right, left);
    }

    auto checksum_text(std::string_view text) -> schema_migration_checksum
    {
        schema_migration_checksum result;
        result.bytes = utils::sha256(text);
        return result;
    }

    void append_text(std::string& output, std::string_view value)
    {
        output += std::to_string(value.size());
        output.push_back(':');
        output.append(value);
    }

    template <std::integral T>
    void append_number(std::string& output, T value)
    {
        append_text(output, std::to_string(value));
    }

    void append_literal(std::string& output, const schema_literal& value)
    {
        std::visit([&output](const auto& item)
            {
                using item_type = std::decay_t<decltype(item)>;
                if constexpr (std::same_as<item_type, bool>)
                    append_text(output, item ? "bool:1" : "bool:0");
                else if constexpr (std::same_as<item_type, std::int64_t>)
                    append_text(output, "int:" + std::to_string(item));
                else
                    append_text(output, "string:" + std::to_string(item.size()) + ":" + item);
            },
            value);
    }

    void append_predicate(std::string& output, const check_predicate& value)
    {
        std::visit([&output](const auto& item)
            {
                using item_type = std::decay_t<decltype(item)>;
                if constexpr (std::same_as<item_type, column_literal_predicate>)
                {
                    append_text(output, "literal");
                    append_text(output, item.column);
                    append_number(output, static_cast<std::uint8_t>(item.comparison));
                    append_literal(output, item.value);
                }
                else if constexpr (std::same_as<item_type, column_set_predicate>)
                {
                    append_text(output, "set");
                    append_text(output, item.column);
                    append_number(output, item.values.size());
                    for (const auto& literal_value : item.values)
                        append_literal(output, literal_value);
                }
                else if constexpr (std::same_as<item_type, column_like_predicate>)
                {
                    append_text(output, "like");
                    append_text(output, item.column);
                    append_text(output, item.pattern);
                }
                else
                {
                    append_text(output, "comparison");
                    append_text(output, item.left_column);
                    append_number(output, static_cast<std::uint8_t>(item.comparison));
                    append_text(output, item.right_column);
                }
            },
            value);
    }

    void append_column(std::string& output, const column_definition& value)
    {
        append_text(output, value.name);
        append_number(output, static_cast<std::uint8_t>(value.type));
        append_number(output, value.length.has_value());
        if (value.length)
            append_number(output, *value.length);
        append_number(output, value.nullable);
        append_number(output, value.primary_key);
        append_number(output, value.auto_generated);
        append_number(output, value.default_value.has_value());
        if (value.default_value)
            std::visit([&output](const auto& default_value)
                {
                    using default_type = std::decay_t<decltype(default_value)>;
                    if constexpr (std::same_as<default_type, current_timestamp_default>)
                        append_text(output, "current_timestamp");
                    else
                    {
                        append_text(output, "literal_default");
                        append_literal(output, default_value);
                    }
                },
                *value.default_value);
    }

    void append_names(std::string& output, const std::vector<std::string>& values)
    {
        append_number(output, values.size());
        for (const auto& value : values)
            append_text(output, value);
    }

    void append_operation(std::string& output, const schema_operation& value)
    {
        std::visit([&output](const auto& operation)
            {
                using operation_type = std::decay_t<decltype(operation)>;
                if constexpr (std::same_as<operation_type, create_table_operation>)
                {
                    append_text(output, "create_table");
                    append_text(output, operation.table.name);
                    append_number(output, operation.table.columns.size());
                    for (const auto& item : operation.table.columns)
                        append_column(output, item);
                    append_number(output, operation.table.indexes.size());
                    for (const auto& item : operation.table.indexes)
                    {
                        append_text(output, item.name);
                        append_names(output, item.columns);
                        append_number(output, item.unique);
                    }
                    append_number(output, operation.table.unique_constraints.size());
                    for (const auto& item : operation.table.unique_constraints)
                    {
                        append_text(output, item.name);
                        append_names(output, item.columns);
                    }
                    append_number(output, operation.table.foreign_keys.size());
                    for (const auto& item : operation.table.foreign_keys)
                    {
                        append_text(output, item.name);
                        append_names(output, item.columns);
                        append_text(output, item.referenced_table);
                        append_names(output, item.referenced_columns);
                        append_number(output, static_cast<std::uint8_t>(item.on_delete));
                    }
                    append_number(output, operation.table.checks.size());
                    for (const auto& item : operation.table.checks)
                    {
                        append_text(output, item.name);
                        append_predicate(output, item.predicate);
                    }
                }
                else if constexpr (std::same_as<operation_type, add_column_operation>)
                {
                    append_text(output, "add_column");
                    append_text(output, operation.table);
                    append_column(output, operation.column);
                }
                else if constexpr (std::same_as<operation_type, add_index_operation>)
                {
                    append_text(output, "add_index");
                    append_text(output, operation.table);
                    append_text(output, operation.index.name);
                    append_names(output, operation.index.columns);
                    append_number(output, operation.index.unique);
                }
                else if constexpr (std::same_as<operation_type, add_unique_constraint_operation>)
                {
                    append_text(output, "add_unique");
                    append_text(output, operation.table);
                    append_text(output, operation.constraint.name);
                    append_names(output, operation.constraint.columns);
                }
                else if constexpr (std::same_as<operation_type, add_foreign_key_operation>)
                {
                    append_text(output, "add_foreign_key");
                    append_text(output, operation.table);
                    append_text(output, operation.constraint.name);
                    append_names(output, operation.constraint.columns);
                    append_text(output, operation.constraint.referenced_table);
                    append_names(output, operation.constraint.referenced_columns);
                    append_number(output, static_cast<std::uint8_t>(operation.constraint.on_delete));
                }
                else
                {
                    append_text(output, "add_check");
                    append_text(output, operation.table);
                    append_text(output, operation.constraint.name);
                    append_predicate(output, operation.constraint.predicate);
                }
            },
            value);
    }

    auto history_error(schema_migration_history_error_code code, std::string text)
        -> schema_migration_history_error
    {
        return {code, std::move(text)};
    }
} // namespace

auto canonical_schema_migration_checksum(const schema_migration& migration)
    -> std::expected<schema_migration_checksum, schema_migration_history_error>
{
    if (!migration.version.valid() || migration.name.empty() || migration.operations.empty())
        return std::unexpected(history_error(schema_migration_history_error_code::invalid_declared_migration,
            "migration requires version, name, and operations"));
    std::string canonical;
    append_text(canonical, "cnetmod.semantic_schema_migration.v1");
    append_number(canonical, migration.version.major);
    append_number(canonical, migration.version.minor);
    append_number(canonical, migration.version.patch);
    append_text(canonical, migration.name);
    append_number(canonical, migration.operations.size());
    for (const auto& operation : migration.operations)
        append_operation(canonical, operation);
    return checksum_text(canonical);
}

auto plan_forward_schema_migrations(std::span<const schema_migration> declared,
    std::span<const applied_schema_migration> applied)
    -> std::expected<forward_schema_migration_plan, schema_migration_history_error>
{
    std::vector<const schema_migration*> ordered;
    ordered.reserve(declared.size());
    for (const auto& migration : declared)
    {
        auto checksum = canonical_schema_migration_checksum(migration);
        if (!checksum)
            return std::unexpected(checksum.error());
        ordered.push_back(&migration);
    }
    std::ranges::sort(ordered, [](const auto* left, const auto* right)
        {
            return version_less(left->version, right->version);
        });
    for (std::size_t index = 1; index < ordered.size(); ++index)
        if (same_version(ordered[index - 1]->version, ordered[index]->version))
            return std::unexpected(history_error(schema_migration_history_error_code::duplicate_declared_version,
                "declared schema migration versions must be unique"));
    std::vector<const applied_schema_migration*> ledger;
    ledger.reserve(applied.size());
    for (const auto& item : applied)
        ledger.push_back(&item);
    std::ranges::sort(ledger, [](const auto* left, const auto* right)
        {
            return version_less(left->version, right->version);
        });
    for (std::size_t index = 1; index < ledger.size(); ++index)
        if (same_version(ledger[index - 1]->version, ledger[index]->version))
            return std::unexpected(history_error(schema_migration_history_error_code::duplicate_applied_version,
                "applied schema migration ledger contains duplicate versions"));
    for (const auto* item : ledger)
    {
        const auto found = std::ranges::find_if(ordered, [item](const auto* migration)
            {
                return same_version(migration->version, item->version);
            });
        if (found == ordered.end())
            return std::unexpected(history_error(schema_migration_history_error_code::unknown_applied_version,
                "applied schema migration is absent from declarations: " + item->version.to_string()));
        auto checksum = canonical_schema_migration_checksum(**found);
        if (*checksum != item->checksum)
            return std::unexpected(history_error(schema_migration_history_error_code::checksum_mismatch,
                "applied schema migration checksum differs from declaration: " + item->version.to_string()));
        if ((*found)->name != item->name)
            return std::unexpected(history_error(schema_migration_history_error_code::name_mismatch,
                "applied schema migration name differs from declaration: " + item->version.to_string()));
    }
    forward_schema_migration_plan plan;
    for (const auto* migration : ordered)
    {
        const auto known = std::ranges::any_of(ledger, [migration](const auto* item)
            {
                return same_version(item->version, migration->version);
            });
        if (!known)
            plan.pending.push_back(migration);
    }
    if (!ledger.empty() && !plan.pending.empty() && version_less(plan.pending.front()->version, ledger.back()->version))
        return std::unexpected(history_error(schema_migration_history_error_code::rollback_detected,
            "migration planning would apply a version older than the applied ledger head"));
    return plan;
}
} // namespace cnetmod::orm
