module;

#include <cnetmod/config.hpp>
#include <cstring>

module cnetmod.protocol.postgresql;

import std;
import :connection;
import cnetmod.core.dns;
import cnetmod.core.error;
import cnetmod.coro.timer;
import cnetmod.executor.async_op;
#ifdef CNETMOD_HAS_SSL
import cnetmod.core.ssl;
#endif

namespace cnetmod::postgresql {
namespace {

    auto read_u16(std::span<const std::uint8_t> input) -> std::uint16_t
    {
        return (std::uint16_t(input[0]) << 8) | input[1];
    }

    auto read_u32(std::span<const std::uint8_t> input) -> std::uint32_t
    {
        return (std::uint32_t(input[0]) << 24) | (std::uint32_t(input[1]) << 16) |
            (std::uint32_t(input[2]) << 8) | input[3];
    }

    auto read_cstring(std::span<const std::uint8_t> input, std::size_t& position)
        -> std::optional<std::string>
    {
        if (position >= input.size())
            return std::nullopt;
        auto end = std::find(input.begin() + static_cast<std::ptrdiff_t>(position), input.end(), 0);
        if (end == input.end())
            return std::nullopt;
        std::string value(reinterpret_cast<const char*>(input.data() + position),
            static_cast<std::size_t>(end - (input.begin() + static_cast<std::ptrdiff_t>(position))));
        position += value.size() + 1;
        return value;
    }

    auto make_error(std::string message, std::string state = {}) -> result_set
    {
        result_set result;
        result.error_msg = std::move(message);
        result.sql_state = std::move(state);
        return result;
    }

    auto normalized_sql(std::string_view input) -> std::string
    {
        std::string out;
        out.reserve(input.size());
        bool literal{};
        for (std::size_t i = 0; i < input.size(); ++i)
        {
            // MySQL's X'ABCD' byte literal is emitted by the shared ORM formatter.
            // PostgreSQL represents the same value as decode('ABCD', 'hex').
            if (!literal && (input[i] == 'X' || input[i] == 'x') &&
                i + 2 < input.size() && input[i + 1] == '\'')
            {
                const auto end = input.find('\'', i + 2);
                if (end != std::string_view::npos)
                {
                    out += "decode('";
                    out.append(input.substr(i + 2, end - i - 2));
                    out += "', 'hex')";
                    i = end;
                    continue;
                }
            }
            const char c = input[i];
            if (c == '\'' && (i == 0 || input[i - 1] != '\\'))
                literal = !literal;
            out.push_back(!literal && c == '`' ? '"' : c);
        }
        auto replace_all = [&out](std::string_view from, std::string_view to)
        {
            std::size_t position{};
            while ((position = out.find(from, position)) != std::string::npos)
            {
                out.replace(position, from.size(), to);
                position += to.size();
            }
        };
        replace_all(" AUTO_INCREMENT", " GENERATED BY DEFAULT AS IDENTITY");
        replace_all(" TINYINT", " SMALLINT");
        replace_all(" MEDIUMINT", " INTEGER");
        replace_all(" INT ", " INTEGER ");
        replace_all(" DATETIME", " TIMESTAMP");
        replace_all(" DOUBLE ", " DOUBLE PRECISION ");
        replace_all(" YEAR", " SMALLINT");
        replace_all(" BINARY(255)", " BYTEA");
        replace_all(" VARBINARY(255)", " BYTEA");
        replace_all(" BLOB", " BYTEA");
        replace_all(" UNSIGNED", "");
        if (auto suffix = out.find(" ENGINE=InnoDB"); suffix != std::string::npos)
            out.erase(suffix);
        return out;
    }

    struct operation_guard
    {
        std::atomic_flag& flag;

        ~operation_guard()
        {
            flag.clear(std::memory_order_release);
        }
    };

    auto retryable_connect_error(const std::error_code& error) noexcept -> bool
    {
        return error == make_error_code(errc::operation_aborted) ||
            error == make_error_code(errc::connection_timed_out) ||
            error == make_error_code(errc::connection_refused) ||
            error == make_error_code(errc::connection_aborted) ||
            error == make_error_code(errc::connection_reset) ||
            error == make_error_code(errc::network_unreachable) ||
            error == make_error_code(errc::host_unreachable) ||
            error == std::errc::operation_canceled ||
            error == std::errc::timed_out ||
            error == std::errc::connection_refused ||
            error == std::errc::connection_aborted ||
            error == std::errc::connection_reset ||
            error == std::errc::network_unreachable ||
            error == std::errc::host_unreachable;
    }

} // namespace

client::client(io_context& context) noexcept : context_(context)
{
    format_options_.backslash_escapes = false;
}

client::~client() = default;

auto client::connect(connection_options options) -> task<result_set>
{
    if (operation_in_progress_.test_and_set(std::memory_order_acquire))
        co_return make_error("another PostgreSQL operation is already in progress");
    operation_guard guard{operation_in_progress_};
    disconnect();
    options_ = std::move(options);
    if (options_.maximum_message_size < 8 || options_.maximum_message_size > 1024ULL * 1024 * 1024)
        co_return make_error("maximum_message_size is outside the supported range");

    happy_eyeballs_options connect_options;
    connect_options.connect_timeout = options_.connect_timeout;
    connect_options.socket_opts.no_delay = true;
    const auto maximum_attempts = std::max<std::size_t>(
        1, options_.maximum_connect_attempts);
    std::expected<connect_result, std::error_code> connected =
        std::unexpected(std::make_error_code(std::errc::host_unreachable));
    for (std::size_t attempt = 1; attempt <= maximum_attempts; ++attempt)
    {
        connected = co_await async_connect_happy_eyeballs(
            context_, options_.host, options_.port, connect_options);
        if (connected || !retryable_connect_error(connected.error()) ||
            attempt == maximum_attempts)
            break;
        co_await async_sleep(context_, options_.connect_retry_backoff * static_cast<int>(attempt));
    }
    if (!connected)
    {
        last_error_ = connected.error();
        co_return make_error("connect: " + connected.error().message());
    }
    socket_ = std::move(connected->sock);

    if (options_.tls != tls_mode::disable)
    {
#ifdef CNETMOD_HAS_SSL
        auto request = detail::ssl_request();
        if (!co_await write_all(request))
            co_return make_error("failed to send SSLRequest");
        std::uint8_t response{};
        if (!co_await read_exact(&response, 1))
            co_return make_error("failed to read SSL negotiation response");
        if (response == 'S')
        {
            auto context = ssl_context::client();
            if (!context)
            {
                disconnect();
                co_return make_error("TLS context: " + context.error().message());
            }
            ssl_context_ = std::make_unique<ssl_context>(std::move(*context));
            const bool verify = options_.tls == tls_mode::verify_ca || options_.tls == tls_mode::verify_full;
            ssl_context_->set_verify_peer(verify);
            if (!options_.tls_ca_file.empty())
            {
                if (auto loaded = ssl_context_->load_ca_file(options_.tls_ca_file); !loaded)
                {
                    disconnect();
                    co_return make_error("failed to load PostgreSQL CA file");
                }
            }
            else if (verify)
            {
                if (auto loaded = ssl_context_->set_default_ca(); !loaded)
                {
                    disconnect();
                    co_return make_error("failed to load system CA certificates");
                }
            }
            if (!options_.tls_cert_file.empty() && !ssl_context_->load_cert_file(options_.tls_cert_file))
            {
                disconnect();
                co_return make_error("failed to load PostgreSQL client certificate");
            }
            if (!options_.tls_key_file.empty() && !ssl_context_->load_key_file(options_.tls_key_file))
            {
                disconnect();
                co_return make_error("failed to load PostgreSQL client key");
            }
            ssl_stream_ = std::make_unique<ssl_stream>(*ssl_context_, context_, socket_);
            ssl_stream_->set_connect_state();
            if (options_.tls == tls_mode::verify_full)
                ssl_stream_->set_hostname(options_.host);
            auto handshake = co_await ssl_stream_->async_handshake();
            if (!handshake)
            {
                auto message = handshake.error().message();
                disconnect(handshake.error());
                co_return make_error("TLS handshake: " + message);
            }
            secure_ = true;
        }
        else if (response != 'N')
        {
            disconnect();
            co_return make_error("invalid SSL negotiation response");
        }
        else if (options_.tls != tls_mode::prefer)
        {
            disconnect();
            co_return make_error("PostgreSQL server rejected required TLS");
        }
#else
        if (options_.tls != tls_mode::prefer)
        {
            disconnect();
            co_return make_error("TLS requested but cnetmod was built without OpenSSL");
        }
#endif
    }

    auto startup = detail::startup_message(options_);
    if (!co_await write_all(startup))
        co_return make_error("failed to send StartupMessage");
    auto authenticated = co_await authenticate();
    if (authenticated.is_err())
        disconnect();
    co_return authenticated;
}

auto client::reconnect() -> task<result_set>
{
    auto saved = options_;
    disconnect();
    co_return co_await connect(std::move(saved));
}

auto client::authenticate() -> task<result_set>
{
    detail::scram_client scram;
    bool scram_started{};
    for (;;)
    {
        auto message = co_await read_message();
        if (!message)
            co_return make_error(message.error());
        auto payload = std::span<const std::uint8_t>(message->payload);
        if (message->type == 'R')
        {
            if (payload.size() < 4)
                co_return make_error("truncated AuthenticationRequest");
            const auto method = read_u32(payload.first(4));
            if (method == 0)
                continue;
            if (method == 3)
            {
                if (!secure_)
                    co_return make_error("cleartext password authentication is refused without TLS");
                if (!co_await write_all(detail::password_message(options_.password)))
                    co_return make_error("failed to send password");
            }
            else if (method == 5)
            {
                if (payload.size() != 8)
                    co_return make_error("invalid MD5 authentication request");
                auto password = detail::md5_password(options_.username, options_.password,
                    std::span<const std::uint8_t, 4>(payload.subspan(4, 4)));
                if (!password)
                    co_return make_error(password.error());
                if (!co_await write_all(detail::password_message(*password)))
                    co_return make_error("failed to send MD5 password");
            }
            else if (method == 10)
            {
                bool supports_sha256{};
                std::size_t position = 4;
                while (position < payload.size())
                {
                    auto mechanism = read_cstring(payload, position);
                    if (!mechanism || mechanism->empty())
                        break;
                    if (*mechanism == "SCRAM-SHA-256")
                        supports_sha256 = true;
                }
                if (!supports_sha256)
                    co_return make_error("server does not offer SCRAM-SHA-256");
                std::string first;
                try
                {
                    first = scram.begin(options_.username);
                }
                catch (const std::exception& error)
                {
                    co_return make_error(error.what());
                }
                scram_started = true;
                if (!co_await write_all(detail::scram_initial_response("SCRAM-SHA-256", first)))
                    co_return make_error("failed to send SCRAM initial response");
            }
            else if (method == 11 && scram_started)
            {
                std::string challenge(reinterpret_cast<const char*>(payload.data() + 4), payload.size() - 4);
                auto response = scram.respond(options_.password, challenge);
                if (!response)
                    co_return make_error(response.error());
                if (!co_await write_all(detail::scram_response(*response)))
                    co_return make_error("failed to send SCRAM proof");
            }
            else if (method == 12 && scram_started)
            {
                std::string final_message(reinterpret_cast<const char*>(payload.data() + 4), payload.size() - 4);
                if (auto verified = scram.verify(final_message); !verified)
                    co_return make_error(verified.error());
            }
            else
                co_return make_error(std::format("unsupported PostgreSQL authentication method {}", method));
        }
        else if (message->type == 'E')
        {
            auto error = detail::parse_error(payload);
            co_return make_error(error.message.empty() ? "PostgreSQL authentication failed" : error.message, error.sql_state);
        }
        else if (message->type == 'S')
        {
            std::size_t position{};
            auto key = read_cstring(payload, position);
            auto value = read_cstring(payload, position);
            if (key && value)
                parameters_.insert_or_assign(std::move(*key), std::move(*value));
        }
        else if (message->type == 'K' && payload.size() == 8)
        {
            process_id_ = read_u32(payload.first(4));
            secret_key_ = read_u32(payload.subspan(4));
        }
        else if (message->type == 'Z')
        {
            connected_ = true;
            transaction_failed_ = !payload.empty() && payload[0] == 'E';
            co_return result_set{};
        }
    }
}

auto client::query(std::string_view sql) -> task<result_set>
{
    if (!connected_)
        co_return make_error("not connected");
    if (operation_in_progress_.test_and_set(std::memory_order_acquire))
        co_return make_error("another PostgreSQL operation is already in progress");
    operation_guard guard{operation_in_progress_};
    auto command = detail::simple_query_message(normalized_sql(sql));
    if (!co_await write_all(command))
        co_return make_error("failed to send query");
    co_return co_await collect_results();
}

auto client::execute(std::string_view sql) -> task<result_set>
{
    return query(sql);
}

auto client::execute(parameterized_query parameters) -> task<result_set>
{
    if (!connected_)
        co_return make_error("not connected");
    if (operation_in_progress_.test_and_set(std::memory_order_acquire))
        co_return make_error("another PostgreSQL operation is already in progress");
    operation_guard guard{operation_in_progress_};
    const auto sql = normalized_sql(parameters.query);
    if (detail::count_postgresql_parameters(sql) != parameters.args.size())
        co_return make_error("PostgreSQL parameter count mismatch");
    auto messages = detail::extended_query_messages({}, sql, parameters.args, true);
    if (messages.size() > options_.maximum_message_size)
        co_return make_error("parameterized query exceeds maximum_message_size");
    if (!co_await write_all(messages))
        co_return make_error("failed to send parameterized query");
    co_return co_await collect_results();
}

auto client::prepare(std::string_view sql, std::string name)
    -> task<std::expected<prepared_statement, std::string>>
{
    if (!connected_)
        co_return std::unexpected("not connected");
    if (operation_in_progress_.test_and_set(std::memory_order_acquire))
        co_return std::unexpected("another PostgreSQL operation is already in progress");
    operation_guard guard{operation_in_progress_};
    if (name.empty())
        name = std::format("cnetmod_{}", ++statement_counter_);
    if (name.find('\0') != std::string::npos)
        co_return std::unexpected("statement name contains NUL");
    const auto normalized = normalized_sql(sql);
    const auto parameter_count = detail::count_postgresql_parameters(normalized);
    if (parameter_count > 65535)
        co_return std::unexpected("PostgreSQL supports at most 65535 statement parameters");
    auto messages = detail::prepare_statement_messages(name, normalized);
    if (messages.size() > options_.maximum_message_size)
        co_return std::unexpected("prepared statement exceeds maximum_message_size");
    if (!co_await write_all(messages))
        co_return std::unexpected("failed to send Parse message");
    auto result = co_await collect_results();
    if (result.is_err())
        co_return std::unexpected(result.error_msg);
    co_return prepared_statement{std::move(name), normalized, parameter_count};
}

auto client::execute(const prepared_statement& statement,
    std::span<const param_value> parameters) -> task<result_set>
{
    if (!connected_)
        co_return make_error("not connected");
    if (!statement.valid())
        co_return make_error("invalid prepared statement");
    if (parameters.size() != statement.parameter_count)
        co_return make_error("prepared statement parameter count mismatch");
    if (operation_in_progress_.test_and_set(std::memory_order_acquire))
        co_return make_error("another PostgreSQL operation is already in progress");
    operation_guard guard{operation_in_progress_};
    auto messages = detail::extended_query_messages(statement.name, {}, parameters, false);
    if (!co_await write_all(messages))
        co_return make_error("failed to bind prepared statement");
    co_return co_await collect_results();
}

auto client::close_statement(const prepared_statement& statement) -> task<result_set>
{
    if (!connected_)
        co_return make_error("not connected");
    if (operation_in_progress_.test_and_set(std::memory_order_acquire))
        co_return make_error("another PostgreSQL operation is already in progress");
    operation_guard guard{operation_in_progress_};
    std::vector<std::uint8_t> message{'C', 0, 0, 0, 0, 'S'};
    message.insert(message.end(), statement.name.begin(), statement.name.end());
    message.push_back(0);
    const auto length = static_cast<std::uint32_t>(message.size() - 1);
    message[1] = static_cast<std::uint8_t>(length >> 24);
    message[2] = static_cast<std::uint8_t>(length >> 16);
    message[3] = static_cast<std::uint8_t>(length >> 8);
    message[4] = static_cast<std::uint8_t>(length);
    message.insert(message.end(), {'S', 0, 0, 0, 4});
    if (!co_await write_all(message))
        co_return make_error("failed to close prepared statement");
    co_return co_await collect_results();
}

auto client::copy_from(std::string_view copy_sql, copy_data_source source)
    -> task<result_set>
{
    if (!connected_)
        co_return make_error("not connected");
    if (!source)
        co_return make_error("COPY source callback is empty");
    if (operation_in_progress_.test_and_set(std::memory_order_acquire))
        co_return make_error("another PostgreSQL operation is already in progress");
    operation_guard guard{operation_in_progress_};
    if (!co_await write_all(detail::simple_query_message(normalized_sql(copy_sql))))
        co_return make_error("failed to start COPY FROM STDIN");
    auto response = co_await read_message();
    if (!response)
        co_return make_error(response.error());
    if (response->type == 'E')
    {
        auto error = detail::parse_error(response->payload);
        co_return make_error(error.message, error.sql_state);
    }
    if (response->type != 'G')
        co_return make_error("server did not enter COPY FROM STDIN mode");
    std::string copy_failure;
    for (;;)
    {
        std::optional<std::vector<std::uint8_t>> chunk;
        try
        {
            chunk = co_await source();
        }
        catch (const std::exception& error)
        {
            copy_failure = error.what();
            break;
        }
        catch (...)
        {
            copy_failure = "COPY source callback failed";
            break;
        }
        if (!chunk)
            break;
        if (chunk->size() + 4 > options_.maximum_message_size)
        {
            copy_failure = "COPY data chunk exceeds maximum_message_size";
            break;
        }
        std::vector<std::uint8_t> message{'d', 0, 0, 0, 0};
        const auto length = static_cast<std::uint32_t>(chunk->size() + 4);
        message[1] = static_cast<std::uint8_t>(length >> 24);
        message[2] = static_cast<std::uint8_t>(length >> 16);
        message[3] = static_cast<std::uint8_t>(length >> 8);
        message[4] = static_cast<std::uint8_t>(length);
        message.insert(message.end(), chunk->begin(), chunk->end());
        if (!co_await write_all(message))
            co_return make_error("failed to stream COPY data");
    }
    if (!copy_failure.empty())
    {
        std::vector<std::uint8_t> fail{'f', 0, 0, 0, 0};
        fail.insert(fail.end(), copy_failure.begin(), copy_failure.end());
        fail.push_back(0);
        const auto length = static_cast<std::uint32_t>(fail.size() - 1);
        fail[1] = static_cast<std::uint8_t>(length >> 24);
        fail[2] = static_cast<std::uint8_t>(length >> 16);
        fail[3] = static_cast<std::uint8_t>(length >> 8);
        fail[4] = static_cast<std::uint8_t>(length);
        if (!co_await write_all(fail))
            co_return make_error("failed to abort COPY FROM STDIN");
        auto aborted = co_await collect_results();
        if (aborted.error_msg.empty())
            aborted.error_msg = std::move(copy_failure);
        co_return aborted;
    }
    const std::array<std::uint8_t, 5> done{'c', 0, 0, 0, 4};
    if (!co_await write_all(done))
        co_return make_error("failed to finish COPY FROM STDIN");
    co_return co_await collect_results();
}

auto client::copy_to(std::string_view copy_sql, copy_data_sink sink)
    -> task<result_set>
{
    if (!connected_)
        co_return make_error("not connected");
    if (!sink)
        co_return make_error("COPY sink callback is empty");
    if (operation_in_progress_.test_and_set(std::memory_order_acquire))
        co_return make_error("another PostgreSQL operation is already in progress");
    operation_guard guard{operation_in_progress_};
    if (!co_await write_all(detail::simple_query_message(normalized_sql(copy_sql))))
        co_return make_error("failed to start COPY TO STDOUT");
    result_set result;
    bool copy_started{};
    std::exception_ptr sink_failure;
    for (;;)
    {
        auto message = co_await read_message();
        if (!message)
            co_return make_error(message.error());
        if (message->type == 'H')
            copy_started = true;
        else if (message->type == 'd')
        {
            if (!copy_started)
                co_return make_error("COPY data received before CopyOutResponse");
            if (!sink_failure)
            {
                try
                {
                    co_await sink(message->payload);
                }
                catch (...)
                {
                    sink_failure = std::current_exception();
                }
            }
        }
        else if (message->type == 'C')
        {
            std::size_t position{};
            auto tag = read_cstring(std::span<const std::uint8_t>(message->payload), position);
            if (tag)
                result.info = *tag;
        }
        else if (message->type == 'E')
        {
            auto error = detail::parse_error(message->payload);
            result.error_msg = error.message;
            result.sql_state = error.sql_state;
        }
        else if (message->type == 'Z')
        {
            if (sink_failure)
                std::rethrow_exception(sink_failure);
            co_return result;
        }
    }
}

auto client::drain_until_ready() -> task<bool>
{
    for (;;)
    {
        auto message = co_await read_message();
        if (!message)
            co_return false;
        if (message->type == 'Z')
            co_return true;
    }
}

auto client::abort_streaming_portal(std::string_view portal) -> task<void>
{
    if (!co_await write_all(detail::streaming_portal_close_messages(portal)))
    {
        disconnect();
        co_return;
    }
    if (!co_await drain_until_ready())
        disconnect();
}

auto client::deliver_batch(std::vector<row>& batch,
    const std::function<task<void>(std::span<const row>)>& consume)
    -> task<std::exception_ptr>
{
    if (batch.empty())
        co_return nullptr;
    try
    {
        co_await consume(std::span<const row>(batch));
    }
    catch (...)
    {
        batch.clear();
        co_return std::current_exception();
    }
    batch.clear();
    co_return nullptr;
}

#if defined(_MSC_VER)
    // MSVC's Release coroutine backend cannot emit the required symmetric tail
    // call for this large portal state machine (C4737). Keep the workaround to
    // this network-bound API; the remainder of the connection implementation
    // continues using the project's Release optimization settings.
    #pragma optimize("", off)
#endif

auto client::query_batches(std::string_view sql, std::size_t batch_size,
    std::function<task<void>(std::span<const row>)> consume) -> task<result_set>
{
    if (batch_size == 0 || batch_size > std::numeric_limits<std::uint32_t>::max() || !consume)
        co_return make_error("invalid query batch consumer");
    if (!connected_)
        co_return make_error("not connected");
    if (operation_in_progress_.test_and_set(std::memory_order_acquire))
        co_return make_error("another PostgreSQL operation is already in progress");
    operation_guard guard{operation_in_progress_};

    const std::string portal = std::format("cnetmod_stream_{}", ++statement_counter_);
    auto start = detail::streaming_portal_start_messages(portal,
        normalized_sql(sql), static_cast<std::uint32_t>(batch_size));
    if (!co_await write_all(start))
        co_return make_error("failed to start streaming portal");

    result_set result;
    std::vector<std::uint32_t> oids;
    std::vector<row> batch;
    batch.reserve(batch_size);
    bool command_complete{};

    for (;;)
    {
        auto message = co_await read_message();
        if (!message)
        {
            disconnect();
            co_return make_error(message.error());
        }
        auto payload = std::span<const std::uint8_t>(message->payload);
        if (message->type == 'T')
        {
            if (payload.size() < 2)
            {
                co_await abort_streaming_portal(portal);
                co_return make_error("truncated RowDescription");
            }
            const auto count = read_u16(payload.first(2));
            if (count > options_.maximum_column_count)
            {
                co_await abort_streaming_portal(portal);
                co_return make_error("PostgreSQL column limit exceeded");
            }
            result.columns.clear();
            oids.clear();
            result.columns.reserve(count);
            oids.reserve(count);
            std::size_t position = 2;
            for (std::uint16_t i = 0; i < count; ++i)
            {
                auto name = read_cstring(payload, position);
                if (!name || position + 18 > payload.size())
                {
                    co_await abort_streaming_portal(portal);
                    co_return make_error("invalid RowDescription");
                }
                column_meta column;
                column.name = *name;
                column.original_name = *name;
                position += 6;
                const auto oid = read_u32(payload.subspan(position, 4));
                position += 4;
                column.native_type = oid;
                oids.push_back(oid);
                const auto width = read_u16(payload.subspan(position, 2));
                position += 2;
                column.type_size = width == 0xffff ? -1 : static_cast<std::int16_t>(width);
                column.type_modifier = static_cast<std::int32_t>(read_u32(payload.subspan(position, 4)));
                position += 4;
                column.format_code = static_cast<std::int16_t>(read_u16(payload.subspan(position, 2)));
                position += 2;
                result.columns.push_back(std::move(column));
            }
        }
        else if (message->type == 'D')
        {
            if (payload.size() < 2)
            {
                co_await abort_streaming_portal(portal);
                co_return make_error("truncated DataRow");
            }
            const auto count = read_u16(payload.first(2));
            if (count != oids.size())
            {
                co_await abort_streaming_portal(portal);
                co_return make_error("DataRow column count mismatch");
            }
            std::size_t position = 2;
            row values;
            values.reserve(count);
            for (std::size_t i = 0; i < count; ++i)
            {
                if (position + 4 > payload.size())
                {
                    co_await abort_streaming_portal(portal);
                    co_return make_error("truncated DataRow field length");
                }
                const auto length = read_u32(payload.subspan(position, 4));
                position += 4;
                if (length == 0xffffffffU)
                {
                    values.push_back(field_value::null());
                    continue;
                }
                if (length > payload.size() - position)
                {
                    co_await abort_streaming_portal(portal);
                    co_return make_error("invalid DataRow field length");
                }
                std::string_view value(reinterpret_cast<const char*>(payload.data() + position), length);
                values.push_back(detail::decode_text_field(oids[i], value));
                position += length;
            }
            batch.push_back(std::move(values));
            if (batch.size() == batch_size)
            {
                auto callback_failure = co_await deliver_batch(batch, consume);
                if (callback_failure)
                {
                    co_await abort_streaming_portal(portal);
                    std::rethrow_exception(callback_failure);
                }
            }
        }
        else if (message->type == 's')
        {
            auto callback_failure = co_await deliver_batch(batch, consume);
            if (callback_failure)
            {
                co_await abort_streaming_portal(portal);
                std::rethrow_exception(callback_failure);
            }
            auto next = detail::streaming_portal_continue_messages(portal, static_cast<std::uint32_t>(batch_size));
            if (!co_await write_all(next))
            {
                disconnect();
                co_return make_error("failed to continue streaming portal");
            }
        }
        else if (message->type == 'C')
        {
            auto callback_failure = co_await deliver_batch(batch, consume);
            if (callback_failure)
            {
                co_await abort_streaming_portal(portal);
                std::rethrow_exception(callback_failure);
            }
            std::size_t position{};
            auto tag = read_cstring(payload, position);
            if (tag)
            {
                result.info = *tag;
                auto split = tag->find_last_of(' ');
                if (split != std::string::npos)
                    (void)std::from_chars(tag->data() + split + 1, tag->data() + tag->size(), result.affected_rows);
            }
            command_complete = true;
            if (!co_await write_all(detail::synchronization_message()))
            {
                disconnect();
                co_return make_error("failed to synchronize streaming portal");
            }
        }
        else if (message->type == 'E')
        {
            auto error = detail::parse_error(payload);
            result.error_msg = error.message;
            result.sql_state = error.sql_state;
            if (!co_await write_all(detail::synchronization_message()))
            {
                disconnect();
                co_return result;
            }
        }
        else if (message->type == 'Z')
        {
            transaction_failed_ = !payload.empty() && payload[0] == 'E';
            if (!command_complete && result.error_msg.empty())
                result.error_msg = "streaming portal ended without CommandComplete";
            co_return result;
        }
    }
}

#if defined(_MSC_VER)
    #pragma optimize("", on)
#endif

auto client::cancel_current_operation() -> task<result_set>
{
    if (!connected_ || process_id_ == 0 || secret_key_ == 0)
        co_return make_error("no active PostgreSQL backend key is available");
    happy_eyeballs_options connect_options;
    connect_options.connect_timeout = options_.connect_timeout;
    connect_options.socket_opts.no_delay = true;
    auto connection = co_await async_connect_happy_eyeballs(
        context_, options_.host, options_.port, connect_options);
    if (!connection)
        co_return make_error("cancel connect: " + connection.error().message());
    std::array<std::uint8_t, 16> request{};
    auto write_u32 = [&request](std::size_t offset, std::uint32_t value)
    {
        request[offset] = static_cast<std::uint8_t>(value >> 24);
        request[offset + 1] = static_cast<std::uint8_t>(value >> 16);
        request[offset + 2] = static_cast<std::uint8_t>(value >> 8);
        request[offset + 3] = static_cast<std::uint8_t>(value);
    };
    write_u32(0, 16);
    write_u32(4, 80877102);
    write_u32(8, process_id_);
    write_u32(12, secret_key_);
    auto sent = co_await async_write_all(context_, connection->sock,
        const_buffer{request.data(), request.size()});
    connection->sock.close();
    if (!sent)
        co_return make_error("failed to send PostgreSQL CancelRequest: " + sent.error().message());
    co_return result_set{};
}

auto client::collect_results() -> task<result_set>
{
    result_set result;
    std::vector<std::uint32_t> oids;
    for (;;)
    {
        auto message = co_await read_message();
        if (!message)
            co_return make_error(message.error());
        auto payload = std::span<const std::uint8_t>(message->payload);
        if (message->type == 'T')
        {
            if (payload.size() < 2)
                co_return make_error("truncated RowDescription");
            const auto count = read_u16(payload.first(2));
            if (count > options_.maximum_column_count)
                co_return make_error("PostgreSQL column limit exceeded");
            result.columns.clear();
            oids.clear();
            result.columns.reserve(count);
            oids.reserve(count);
            std::size_t position = 2;
            for (std::uint16_t i = 0; i < count; ++i)
            {
                auto name = read_cstring(payload, position);
                if (!name || position + 18 > payload.size())
                    co_return make_error("invalid RowDescription");
                column_meta column;
                column.name = *name;
                column.original_name = *name;
                const auto table_oid = read_u32(payload.subspan(position, 4));
                position += 4;
                const auto attribute = read_u16(payload.subspan(position, 2));
                position += 2;
                (void)table_oid;
                (void)attribute;
                const auto oid = read_u32(payload.subspan(position, 4));
                position += 4;
                column.native_type = oid;
                oids.push_back(oid);
                const auto width = read_u16(payload.subspan(position, 2));
                position += 2;
                column.type_size = width == 0xffff ? -1 : static_cast<std::int16_t>(width);
                column.type_modifier = static_cast<std::int32_t>(read_u32(payload.subspan(position, 4)));
                position += 4;
                column.format_code = static_cast<std::int16_t>(read_u16(payload.subspan(position, 2)));
                position += 2;
                result.columns.push_back(std::move(column));
            }
        }
        else if (message->type == 'D')
        {
            if (result.rows.size() >= options_.maximum_row_count)
                co_return make_error("PostgreSQL row limit exceeded");
            if (payload.size() < 2)
                co_return make_error("truncated DataRow");
            const auto count = read_u16(payload.first(2));
            if (count != oids.size())
                co_return make_error("DataRow column count mismatch");
            std::size_t position = 2;
            row values;
            values.reserve(count);
            for (std::size_t i = 0; i < count; ++i)
            {
                if (position + 4 > payload.size())
                    co_return make_error("truncated DataRow field length");
                const auto length = read_u32(payload.subspan(position, 4));
                position += 4;
                if (length == 0xffffffffU)
                {
                    values.push_back(field_value::null());
                    continue;
                }
                if (length > payload.size() - position)
                    co_return make_error("invalid DataRow field length");
                std::string_view value(reinterpret_cast<const char*>(payload.data() + position), length);
                values.push_back(detail::decode_text_field(oids[i], value));
                position += length;
            }
            result.rows.push_back(std::move(values));
        }
        else if (message->type == 'C')
        {
            std::size_t position{};
            auto tag = read_cstring(payload, position);
            if (tag)
            {
                result.info = *tag;
                auto split = tag->find_last_of(' ');
                if (split != std::string::npos)
                {
                    std::uint64_t count{};
                    auto parsed = std::from_chars(tag->data() + split + 1, tag->data() + tag->size(), count);
                    if (parsed.ec == std::errc{})
                        result.affected_rows = count;
                }
            }
        }
        else if (message->type == 'E')
        {
            auto error = detail::parse_error(payload);
            result.error_msg = error.message.empty() ? "PostgreSQL query failed" : error.message;
            if (!error.detail.empty())
                result.error_msg += ": " + error.detail;
            result.sql_state = error.sql_state;
        }
        else if (message->type == 'S')
        {
            std::size_t position{};
            auto key = read_cstring(payload, position);
            auto value = read_cstring(payload, position);
            if (key && value)
                parameters_.insert_or_assign(std::move(*key), std::move(*value));
        }
        else if (message->type == 'K' && payload.size() == 8)
        {
            process_id_ = read_u32(payload.first(4));
            secret_key_ = read_u32(payload.subspan(4));
        }
        else if (message->type == 'Z')
        {
            transaction_failed_ = !payload.empty() && payload[0] == 'E';
            if (!result.rows.empty() && !result.rows.front().empty())
            {
                const auto& value = result.rows.front().front();
                if (value.is_int64() && value.get_int64() >= 0)
                    result.last_insert_id = static_cast<std::uint64_t>(value.get_int64());
                else if (value.is_uint64())
                    result.last_insert_id = value.get_uint64();
            }
            co_return result;
        }
    }
}

auto client::terminate() -> task<void>
{
    if (connected_)
    {
        auto message = detail::terminate_message();
        (void)co_await write_all(message);
#ifdef CNETMOD_HAS_SSL
        if (ssl_stream_)
            (void)co_await ssl_stream_->async_shutdown();
#endif
    }
    disconnect();
    co_return;
}

auto client::write_all(std::span<const std::uint8_t> bytes) -> task<bool>
{
    if (bytes.empty() || bytes.size() > options_.maximum_message_size)
    {
        disconnect(std::make_error_code(std::errc::message_size));
        co_return false;
    }
    const_buffer buffer{bytes.data(), bytes.size()};
#ifdef CNETMOD_HAS_SSL
    if (ssl_stream_)
    {
        auto written = co_await ssl_stream_->async_write_all(buffer);
        if (!written)
        {
            disconnect(written.error());
            co_return false;
        }
        co_return true;
    }
#endif
    auto written = co_await async_write_all(context_, socket_, buffer);
    if (!written)
    {
        disconnect(written.error());
        co_return false;
    }
    co_return true;
}

auto client::read_exact(std::uint8_t* destination, std::size_t length) -> task<bool>
{
    std::size_t received{};
    while (received < length)
    {
        mutable_buffer buffer{destination + received, length - received};
#ifdef CNETMOD_HAS_SSL
        std::expected<std::size_t, std::error_code> part;
        if (ssl_stream_)
            part = co_await ssl_stream_->async_read(buffer);
        else
            part = co_await async_read(context_, socket_, buffer);
#else
        auto part = co_await async_read(context_, socket_, buffer);
#endif
        if (!part || *part == 0)
        {
            disconnect(part ? std::make_error_code(std::errc::connection_reset) : part.error());
            co_return false;
        }
        received += *part;
    }
    co_return true;
}

auto client::read_message() -> task<std::expected<detail::backend_message, std::string>>
{
    std::array<std::uint8_t, 5> header{};
    if (!co_await read_exact(header.data(), header.size()))
        co_return std::unexpected("connection lost while reading PostgreSQL message");
    const auto length = read_u32(std::span<const std::uint8_t>(header).subspan(1));
    if (length < 4 || length > options_.maximum_message_size)
    {
        disconnect();
        co_return std::unexpected("invalid PostgreSQL message length");
    }
    std::vector<std::uint8_t> wire(length + 1);
    std::copy(header.begin(), header.end(), wire.begin());
    if (length > 4 && !co_await read_exact(wire.data() + 5, length - 4))
        co_return std::unexpected("connection lost while reading PostgreSQL payload");
    co_return detail::parse_message(wire);
}

void client::disconnect(std::error_code error) noexcept
{
    connected_ = false;
    secure_ = false;
    transaction_failed_ = false;
    last_error_ = error;
    parameters_.clear();
    process_id_ = 0;
    secret_key_ = 0;
#ifdef CNETMOD_HAS_SSL
    ssl_stream_.reset();
    ssl_context_.reset();
#endif
    socket_.close();
}

auto client::is_open() const noexcept -> bool
{
    return connected_ && socket_.is_open();
}

auto client::secure_channel() const noexcept -> bool
{
    return secure_;
}

auto client::last_error() const noexcept -> std::error_code
{
    return last_error_;
}

auto client::current_format_opts() const noexcept -> const format_options&
{
    return format_options_;
}

auto client::server_parameters() const noexcept -> const std::unordered_map<std::string, std::string>&
{
    return parameters_;
}

auto client::backend_process_id() const noexcept -> std::uint32_t
{
    return process_id_;
}

auto client::backend_secret_key() const noexcept -> std::uint32_t
{
    return secret_key_;
}

void client::append_insert_returning(std::string& sql, std::string_view column) const
{
    sql += " RETURNING \"";
    for (char c : column)
    {
        if (c == '"')
            sql += "\"\"";
        else
            sql.push_back(c);
    }
    sql += '"';
}

} // namespace cnetmod::postgresql
