set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v145)

if(DEFINED ENV{VCPKG_VISUAL_STUDIO_PATH})
    set(VCPKG_VISUAL_STUDIO_PATH "$ENV{VCPKG_VISUAL_STUDIO_PATH}")
endif()
