include_guard(GLOBAL)

# Both package managers expose CMake targets. Keep target mapping here; their
# toolchain validation and installation remain in their separate entry points.
macro(cnetmod_configure_package_dependencies)
    set(CNETMOD_USE_SYSTEM_DEPS ON)
    set(CNETMOD_USE_ICU_SUBMODULE OFF CACHE BOOL
        "Use the bundled ICU submodule when available" FORCE)
    cnetmod_configure_stdexec()

    set(CNETMOD_HAS_PUGIXML OFF)
    if(CNETMOD_ENABLE_ORM)
        find_package(pugixml CONFIG REQUIRED)
        foreach(_target pugixml::pugixml pugixml-static pugixml)
            if(TARGET "${_target}" AND NOT CNETMOD_PUGIXML_TARGET)
                set(CNETMOD_PUGIXML_TARGET "${_target}")
            endif()
        endforeach()
        if(NOT CNETMOD_PUGIXML_TARGET)
            message(FATAL_ERROR "pugixml package did not provide a supported CMake target")
        endif()
        set(CNETMOD_HAS_PUGIXML ON)
    endif()

    set(CNETMOD_HAS_ZLIB OFF)
    if(CNETMOD_ENABLE_HTTP OR CNETMOD_ENABLE_GRPC OR CNETMOD_ENABLE_KAFKA OR CNETMOD_ENABLE_MONGODB)
        find_package(ZLIB REQUIRED)
        set(CNETMOD_HAS_ZLIB ON)
    endif()

    set(CNETMOD_HAS_ZSTD OFF)
    if(CNETMOD_ENABLE_GRPC OR CNETMOD_ENABLE_KAFKA)
        find_package(zstd CONFIG QUIET)
        foreach(_target zstd::libzstd_static zstd::libzstd_shared zstd::zstd)
            if(TARGET "${_target}" AND NOT CNETMOD_ZSTD_TARGET)
                set(CNETMOD_ZSTD_TARGET "${_target}")
            endif()
        endforeach()
        if(CNETMOD_ZSTD_TARGET)
            set(CNETMOD_HAS_ZSTD ON)
        endif()
    endif()

    set(CNETMOD_HAS_BROTLI OFF)
    if(CNETMOD_ENABLE_GRPC)
        find_package(unofficial-brotli CONFIG QUIET)
        if(TARGET unofficial::brotli::brotlienc AND TARGET unofficial::brotli::brotlidec)
            set(CNETMOD_BROTLI_TARGETS unofficial::brotli::brotlienc unofficial::brotli::brotlidec)
            set(CNETMOD_HAS_BROTLI ON)
        endif()
    endif()

    option(CNETMOD_ENABLE_LZ4 "Enable Kafka LZ4 compression" ON)
    set(CNETMOD_HAS_LZ4 OFF)
    if(CNETMOD_ENABLE_KAFKA AND CNETMOD_ENABLE_LZ4)
        find_package(lz4 CONFIG QUIET)
        find_package(LZ4 CONFIG QUIET)
        foreach(_target lz4::lz4 LZ4::lz4 LZ4::LZ4 unofficial::lz4::lz4 lz4_static lz4_shared)
            if(TARGET "${_target}" AND NOT CNETMOD_LZ4_TARGET)
                set(CNETMOD_LZ4_TARGET "${_target}")
            endif()
        endforeach()
        if(CNETMOD_LZ4_TARGET)
            set(CNETMOD_HAS_LZ4 ON)
        endif()
    endif()

    option(CNETMOD_ENABLE_LEVELDB "Enable LevelDB-backed Raft storage" ON)
    set(CNETMOD_HAS_LEVELDB OFF)
    if(CNETMOD_ENABLE_RAFT AND CNETMOD_ENABLE_LEVELDB)
        find_package(leveldb CONFIG QUIET)
        find_package(LevelDB CONFIG QUIET)
        foreach(_target leveldb leveldb::leveldb LevelDB::LevelDB)
            if(TARGET "${_target}" AND NOT CNETMOD_LEVELDB_TARGET)
                set(CNETMOD_LEVELDB_TARGET "${_target}")
            endif()
        endforeach()
        if(NOT CNETMOD_LEVELDB_TARGET)
            message(FATAL_ERROR "LevelDB was requested but its package target is unavailable")
        endif()
        set(CNETMOD_HAS_LEVELDB ON)
    endif()

    set(CNETMOD_HAS_ICU OFF)
    if(CNETMOD_ENABLE_POSTGRESQL)
        find_package(ICU REQUIRED COMPONENTS uc i18n)
        if(NOT TARGET ICU::uc OR NOT TARGET ICU::i18n)
            message(FATAL_ERROR "ICU package must provide ICU::uc and ICU::i18n")
        endif()
        set(CNETMOD_HAS_ICU ON)
    endif()
endmacro()
