include_guard(GLOBAL)

# Native CMake build: use installed libraries and the pinned 3rdparty sources.
get_filename_component(_cnetmod_toolchain_name "${CMAKE_TOOLCHAIN_FILE}" NAME)
if(_cnetmod_toolchain_name STREQUAL "vcpkg.cmake" OR
   _cnetmod_toolchain_name STREQUAL "conan_toolchain.cmake")
    message(FATAL_ERROR
        "system mode cannot use a vcpkg/Conan toolchain; select the matching dependency mode")
endif()

macro(cnetmod_configure_provider_dependencies)
    option(CNETMOD_USE_SYSTEM_DEPS
        "Prefer installed system libraries before bundled 3rdparty sources"
        ON)
    cnetmod_configure_stdexec()
    cnetmod_configure_pugixml()
    cnetmod_configure_zlib()
    cnetmod_configure_zstd()
    cnetmod_configure_brotli()
    cnetmod_configure_lz4()
    cnetmod_configure_leveldb()
    cnetmod_configure_icu()
    cnetmod_print_system_install_hints()
endmacro()

function(cnetmod_print_system_install_hints)
    if(NOT UNIX OR APPLE)
        return()
    endif()

    set(_arch)
    set(_ubuntu)
    set(_centos)
    if((CNETMOD_ENABLE_HTTP OR CNETMOD_ENABLE_GRPC OR CNETMOD_ENABLE_KAFKA OR
        CNETMOD_ENABLE_MONGODB) AND NOT CNETMOD_HAS_ZLIB)
        list(APPEND _arch zlib)
        list(APPEND _ubuntu zlib1g-dev)
        list(APPEND _centos zlib-devel)
    endif()
    if((CNETMOD_ENABLE_GRPC OR CNETMOD_ENABLE_KAFKA) AND NOT CNETMOD_HAS_ZSTD)
        list(APPEND _arch zstd)
        list(APPEND _ubuntu libzstd-dev)
        list(APPEND _centos libzstd-devel)
    endif()
    if(CNETMOD_ENABLE_GRPC AND NOT CNETMOD_HAS_BROTLI)
        list(APPEND _arch brotli)
        list(APPEND _ubuntu libbrotli-dev)
        list(APPEND _centos brotli-devel)
    endif()
    if(CNETMOD_ENABLE_KAFKA AND CNETMOD_ENABLE_LZ4 AND NOT CNETMOD_HAS_LZ4)
        list(APPEND _arch lz4)
        list(APPEND _ubuntu liblz4-dev)
        list(APPEND _centos lz4-devel)
    endif()
    if(CNETMOD_ENABLE_RAFT AND CNETMOD_ENABLE_LEVELDB AND NOT CNETMOD_HAS_LEVELDB)
        list(APPEND _arch leveldb)
        list(APPEND _ubuntu libleveldb-dev)
        list(APPEND _centos leveldb-devel)
    endif()
    if(CNETMOD_USE_MIMALLOC AND NOT CNETMOD_USING_MIMALLOC)
        list(APPEND _arch mimalloc)
        list(APPEND _ubuntu libmimalloc-dev)
        list(APPEND _centos mimalloc-devel)
    endif()

    if(_arch)
        list(JOIN _arch " " _arch_packages)
        list(JOIN _ubuntu " " _ubuntu_packages)
        list(JOIN _centos " " _centos_packages)
        message(STATUS "Missing optional system dependencies; install to enable their features:")
        message(STATUS "  Arch:   sudo pacman -S --needed ${_arch_packages}")
        message(STATUS "  Ubuntu: sudo apt install ${_ubuntu_packages}")
        message(STATUS "  CentOS: sudo dnf install ${_centos_packages}")
    endif()
endfunction()
