module;

#include <cnetmod/config.hpp>

export module cnetmod.protocol.http:server;

import std;
import cnetmod.protocol.http.semantics;
import :parser;
import :request;
import :response;
import :router;
import :cookie;
import cnetmod.core.error;
import cnetmod.core.buffer;
import cnetmod.core.socket;
import cnetmod.core.address;
import cnetmod.core.file;
import cnetmod.io.io_context;
import cnetmod.coro.task;
import cnetmod.coro.cancel;
import cnetmod.coro.spawn;
import cnetmod.executor.async_op;
import cnetmod.executor.pool;
import cnetmod.protocol.tcp;
import cnetmod.utils.concurrent_containers.atomic_rw_latch;

#ifdef CNETMOD_HAS_SSL
import cnetmod.core.ssl;
#endif

import cnetmod.protocol.http.v2.session;

namespace cnetmod::http {

// =============================================================================
// MIME Type Inference
// =============================================================================

export auto guess_mime_type(std::string_view ext) noexcept -> std::string_view;

// =============================================================================
// Static File Serving
// =============================================================================

export struct static_file_options
{
    std::filesystem::path root;
    std::string index_file = "index.html";
};

export auto serve_dir(static_file_options opts) -> handler_fn;

// =============================================================================
// File Upload Saving
// =============================================================================

export struct upload_options
{
    std::filesystem::path save_dir;
    std::string default_filename = "upload.bin";
    std::size_t max_size = 32 * 1024 * 1024; // 32MB
};

export auto save_upload(upload_options opts) -> handler_fn;

export struct response_header_options
{
    bool emit_server = true;
    bool emit_date = true;
};

// =============================================================================
// Date Cache
// =============================================================================

class date_cache
{
public:
    /// Snapshot the RFC 9110 IMF-fixdate into caller-owned stack storage.
    /// Keeping the fixed-width representation out of std::string avoids a
    /// heap allocation for every normal server response.
    [[nodiscard]] auto get() -> std::array<char, 29U>;

private:
    static constexpr std::size_t date_size = 29U;
    static constexpr std::size_t word_count = 4U;

    /// The date is a read-mostly value shared by every server worker.  A
    /// reader must not perform a contended read-modify-write merely to copy
    /// it: that would bounce one cache line between all workers on every
    /// response.  Writers publish four atomic words under this sequence;
    /// refreshes happen at most once per second.
    std::atomic<std::time_t> cached_time_{0};
    std::atomic<std::uint32_t> sequence_{};
    std::atomic_flag refreshing_{};
    alignas(64) std::array<std::atomic<std::uint64_t>, word_count> words_{};
};

// =============================================================================
// http::server — Advanced HTTP Server
// =============================================================================

export class server
{
public:
    /// Single-threaded mode
    explicit server(io_context& ctx);

    /// Multi-core mode
    explicit server(server_context& sctx);

#ifdef CNETMOD_HAS_SSL
    /// Configure TLS
    void set_ssl_context(ssl_context& ssl_ctx);
#endif

    /// Listen on specified address and port
    auto listen(std::string_view host, std::uint16_t port,
        socket_options opts = {.reuse_address = true})
        -> std::expected<void, std::error_code>;

    /**
     * @brief Returns the endpoint selected by the listening socket.
     *
     * This also exposes the operating-system-assigned port after listen() is
     * called with port zero, which avoids fixed-port races in embedded servers
     * and integration tests.
     *
     * @return The bound endpoint, or bad_descriptor when the server is not
     * listening.
     */
    [[nodiscard]] auto local_endpoint()
        -> std::expected<endpoint, std::error_code>;

    /// Set router
    void set_router(router r);

    /**
     * @brief Registers a middleware, ignoring empty optional components.
     *
     * Empty components do not occupy a pipeline slot or add request-time work.
     */
    void use(middleware_fn mw);

    /// Set max concurrent connections
    void set_max_connections(std::size_t n);

    /// Configure headers generated by the server before route execution.
    void set_response_header_options(response_header_options options) noexcept;

    /// Get current active connection count
    [[nodiscard]] auto active_connections() const noexcept -> std::size_t;

    /// Run server (accept loop)
    auto run() -> task<void>;

    /**
     * @brief Stops admission and cancels the pending accept operation.
     *
     * Call on the accept event loop. Keep that loop running until run() has
     * completed; active connections have their own completion lifetime.
     */
    void stop();

    /**
     * @brief Interrupts socket I/O for current and queued connections.
     *
     * Call stop() first to end admission. This is a terminal operation for
     * this server instance. Keep worker event loops alive until connections
     * finish; this does not forcibly destroy handlers awaiting non-socket work.
     */
    void abort_connections() noexcept;

private:
    struct conn_count_guard;
    struct connection_registration;

    auto handle_connection(socket client, io_context& io, conn_count_guard ownership) -> task<void>;

    auto handle_h1_clear(socket& client, io_context& io,
        const char* initial_data, std::size_t initial_len,
        cancel_token& cancellation) -> task<void>;

    auto handle_h2(socket& client, io_context& io,
        std::span<const std::byte> initial,
        cancel_token& cancellation) -> task<void>;

    auto make_h2_streaming_handler(io_context& io, socket& client)
        -> v2::streaming_server_handler;

#ifdef CNETMOD_HAS_SSL
    auto handle_h1_tls(socket& client, io_context& io, ssl_stream& ssl,
        cancel_token& cancellation) -> task<void>;
    auto handle_h2_tls(socket& client, io_context& io, ssl_stream& ssl,
        cancel_token& cancellation) -> task<void>;
#endif

    auto execute_chain(request_context& ctx, handler_fn& handler,
        std::size_t idx = 0) -> task<void>;

    auto send_chunked_response(io_context& io, socket& client, response& resp,
        cancel_token& cancellation) -> task<void>;

#ifdef CNETMOD_HAS_SSL
    auto send_chunked_response_tls(io_context& io, ssl_stream& ssl,
        response& resp, cancel_token& cancellation) -> task<void>;
#endif

    io_context& ctx_;
    server_context* sctx_ = nullptr;
    std::unique_ptr<tcp::acceptor> acc_;
    router router_;
    std::vector<middleware_fn> middlewares_;
    std::string host_;
    std::uint16_t port_ = 0;
    bool running_ = false;
    cancel_token accept_cancellation_;
    std::size_t max_connections_ = 0;
    std::atomic<std::size_t> active_connections_{0};
    concurrent_containers::atomic_rw_latch connections_latch_;
    connection_registration* connections_{};
    bool connections_aborted_{};
    date_cache date_cache_;
    response_header_options response_headers_;
#ifdef CNETMOD_HAS_SSL
    ssl_context* ssl_ctx_ = nullptr;
#endif
};

} // namespace cnetmod::http
