module cnetmod.protocol.http;

import std;
import :router;
import :semantics;
import :parser;
import :request;
import :response;
import :multipart;
import :sse;
import cnetmod.core.error;
import cnetmod.core.buffer;
import cnetmod.core.socket;
import cnetmod.io.io_context;
import cnetmod.coro.task;
import cnetmod.executor.async_op;

namespace cnetmod::http {

namespace detail {
auto parse_pattern(std::string_view pattern) -> std::vector<segment> { std::vector<segment> out; if (pattern.starts_with('/')) pattern.remove_prefix(1); while (!pattern.empty()) { auto slash=pattern.find('/'); auto part=slash==std::string_view::npos?pattern:pattern.substr(0,slash); if (part.starts_with(':')) out.push_back({segment_kind::param,std::string(part.substr(1))}); else if (part.starts_with('*')) { out.push_back({segment_kind::wildcard,std::string(part.size()>1?part.substr(1):"path")}); break; } else out.push_back({segment_kind::exact,std::string(part)}); if(slash==std::string_view::npos) break; pattern.remove_prefix(slash+1); } return out; }
auto split_path(std::string_view path) -> std::vector<std::string_view> { std::vector<std::string_view> out; if(path.starts_with('/')) path.remove_prefix(1); while(!path.empty()) { auto slash=path.find('/'); if(slash==std::string_view::npos) { out.push_back(path); break; } if(slash) out.push_back(path.substr(0,slash)); path.remove_prefix(slash+1); } return out; }
auto route_specificity(const std::vector<segment>& segs,bool any,std::uint64_t order)->route_score { route_score r; r.segment_count=static_cast<int>(segs.size()); r.method_cost=any; r.order=order; for(auto& s:segs) { if(s.kind==segment_kind::exact) ++r.literal_count; else if(s.kind==segment_kind::param) ++r.param_count; else ++r.wildcard_count; } return r; }
auto better_score(const route_score&a,const route_score&b) noexcept -> bool { if(a.wildcard_count!=b.wildcard_count)return a.wildcard_count<b.wildcard_count; if(a.param_count!=b.param_count)return a.param_count<b.param_count; if(a.literal_count!=b.literal_count)return a.literal_count>b.literal_count; if(a.segment_count!=b.segment_count)return a.segment_count>b.segment_count; if(a.method_cost!=b.method_cost)return a.method_cost<b.method_cost; return a.order<b.order; }
auto is_static_route(const std::vector<segment>& segs) noexcept -> bool { return std::ranges::all_of(segs,[](const segment&s){return s.kind==segment_kind::exact;}); }
auto first_literal_segment(const std::vector<segment>& segs)->std::optional<std::string>{ if(!segs.empty()&&segs.front().kind==segment_kind::exact)return segs.front().value; return {}; }
auto canonical_from_segments(const std::vector<segment>& segs)->std::string { if(segs.empty())return "/"; std::string out; for(auto&s:segs){out.push_back('/');out+=s.value;}return out; }
auto canonical_from_parts(const std::vector<std::string_view>& parts)->std::string { if(parts.empty())return "/";std::string out;for(auto p:parts){out.push_back('/');out+=p;}return out; }
auto method_path_key(std::optional<http_method> method,std::string_view path)->std::string { return std::string(method?method_to_string(*method):"*")+" "+std::string(path); }
auto method_bucket_key(std::optional<http_method> method,std::string_view first)->std::string { return method_path_key(method,first); }
}

auto route_params::get(std::string_view key) const noexcept -> std::string_view { auto it=named.find(std::string(key)); return it==named.end()?std::string_view{}:std::string_view{it->second}; }
request_context::request_context(io_context&c,socket&s,const request_parser&p,response&r,route_params x):ctx_(c),sock_(s),resp_(r),params_(std::move(x)),headers_ptr_(&p.headers()),method_(p.method()),body_(p.body()){init_path_query(p.uri());}
request_context::request_context(io_context&c,socket&s,std::string_view m,std::string_view u,const header_map&h,std::string_view b,response&r,route_params x,std::shared_ptr<request_body_stream> stream):ctx_(c),sock_(s),resp_(r),params_(std::move(x)),headers_ptr_(&h),method_(m),body_storage_(b),body_(body_storage_),body_stream_(std::move(stream)){init_path_query(u);}
auto request_context::method()const noexcept->std::string_view{return method_;} auto request_context::method_enum()const noexcept->std::optional<http_method>{return string_to_method(method_);} auto request_context::path()const noexcept->std::string_view{return path_;} auto request_context::query_string()const noexcept->std::string_view{return query_;} auto request_context::uri()const noexcept->std::string_view{return uri_;} auto request_context::headers()const noexcept->const header_map&{return *headers_ptr_;}
auto request_context::body()const->std::string_view{drain_available_body_chunks();return body_;} auto request_context::has_body_stream()const noexcept->bool{return body_stream_!=nullptr;}
auto request_context::receive_body_chunk()->task<std::optional<request_body_chunk>>{if(!body_stream_)co_return std::nullopt;co_return co_await body_stream_->receive();}
auto request_context::read_full_body()->task<std::string_view>{if(!body_stream_||body_stream_drained_){drain_available_body_chunks();co_return body_;}drain_available_body_chunks();while(auto c=co_await body_stream_->receive())body_storage_.append(reinterpret_cast<const char*>(c->data()),c->size());body_=body_storage_;body_stream_drained_=true;co_return body_;}
auto request_context::get_header(std::string_view key)const->std::string_view{auto it=headers_ptr_->find(std::string(key));return it==headers_ptr_->end()?std::string_view{}:std::string_view{it->second};} auto request_context::param(std::string_view n)const noexcept->std::string_view{return params_.get(n);} auto request_context::wildcard()const noexcept->std::string_view{return params_.wildcard;} auto request_context::params()const noexcept->const route_params&{return params_;}
void request_context::text(int s,std::string_view b){resp_.set_status(s);resp_.set_header("Content-Type","text/plain; charset=utf-8");resp_.set_body(std::string(b));} void request_context::json(int s,std::string_view b){resp_.set_status(s);resp_.set_header("Content-Type","application/json; charset=utf-8");resp_.set_body(std::string(b));} void request_context::html(int s,std::string_view b){resp_.set_status(s);resp_.set_header("Content-Type","text/html; charset=utf-8");resp_.set_body(std::string(b));} void request_context::redirect(std::string_view l,int c){resp_.set_status(c);resp_.set_header("Location",l);} void request_context::not_found(){text(status::not_found,"404 Not Found");}
auto request_context::sse_begin(int s)->task<bool>{if(sse_started_)co_return true;resp_.set_status(s);sse::prepare(resp_,sse::response_options{.status_code=s});auto h=resp_.serialize();auto w=co_await async_write_all(ctx_,sock_,const_buffer{h.data(),h.size()});if(!w)co_return false;sse_started_=true;co_return true;} auto request_context::sse_send(std::string_view d,std::string_view e)->task<bool>{if(!(co_await sse_begin()))co_return false;auto f=sse::data(d,e);auto w=co_await async_write_all(ctx_,sock_,const_buffer{f.data(),f.size()});co_return w.has_value();} auto request_context::sse_json(std::string_view j,std::string_view e)->task<bool>{co_return co_await sse_send(j,e);} auto request_context::sse_done()->task<bool>{if(!(co_await sse_begin()))co_return false;auto f=sse::done();auto w=co_await async_write_all(ctx_,sock_,const_buffer{f.data(),f.size()});co_return w.has_value();}
auto request_context::parse_form()->std::expected<const form_data*,std::error_code>{if(form_cache_)return &*form_cache_;auto ct=get_header("Content-Type");if(ct.empty())return std::unexpected(make_error_code(http_errc::invalid_multipart));auto r=http::parse_form(ct,body());if(!r)return std::unexpected(r.error());form_cache_=std::move(*r);return &*form_cache_;} auto request_context::resp()noexcept->response&{return resp_;} auto request_context::io_ctx()noexcept->io_context&{return ctx_;} auto request_context::raw_socket()noexcept->socket&{return sock_;}
void request_context::drain_available_body_chunks()const{if(!body_stream_||body_stream_drained_)return;while(auto c=body_stream_->try_receive())body_storage_.append(reinterpret_cast<const char*>(c->data()),c->size());body_=body_storage_;if(body_stream_->is_closed())body_stream_drained_=true;} void request_context::init_path_query(std::string_view u){uri_=std::string(u);auto q=u.find('?');path_=std::string(u.substr(0,q));if(q!=std::string_view::npos)query_=std::string(u.substr(q+1));}

auto router::get(std::string_view p,handler_fn f)->router&{return add(http_method::GET,p,std::move(f));} auto router::post(std::string_view p,handler_fn f)->router&{return add(http_method::POST,p,std::move(f));} auto router::put(std::string_view p,handler_fn f)->router&{return add(http_method::PUT,p,std::move(f));} auto router::del(std::string_view p,handler_fn f)->router&{return add(http_method::DELETE_,p,std::move(f));} auto router::patch(std::string_view p,handler_fn f)->router&{return add(http_method::PATCH,p,std::move(f));} auto router::any(std::string_view p,handler_fn f)->router&{return add_route({},p,std::move(f));}
auto router::add(http_method m,std::string_view p,handler_fn f)->router&{return add_route(m,p,std::move(f));}
auto router::add_route(std::optional<http_method> m,std::string_view p,handler_fn f)->router&{auto segs=detail::parse_pattern(p);auto order=next_order_++;auto idx=entries_.size();auto stat=detail::is_static_route(segs);auto first=detail::first_literal_segment(segs);auto canonical=detail::canonical_from_segments(segs);entries_.push_back({m,std::move(segs),std::move(f),{},order});auto&e=entries_.back();e.score=detail::route_specificity(e.segments,!m,order);if(stat)exact_index_[detail::method_path_key(m,canonical)].push_back(idx);else if(first)first_literal_index_[detail::method_bucket_key(m,*first)].push_back(idx);else generic_indices_.push_back(idx);return *this;}
auto router::find_exact(http_method m,std::string_view p)const->const route_entry*{const route_entry*best=nullptr;auto find=[&](std::optional<http_method>x){auto it=exact_index_.find(detail::method_path_key(x,p));if(it==exact_index_.end())return;for(auto i:it->second){auto&e=entries_[i];if(!best||detail::better_score(e.score,best->score))best=&e;}};find(m);find({});return best;}
auto router::try_match(const std::vector<detail::segment>&s,const std::vector<std::string_view>&p,route_params&o)->bool{std::size_t pi=0;for(auto&x:s){if(x.kind==detail::segment_kind::wildcard){std::string r;for(;pi<p.size();++pi){if(!r.empty())r+='/';r+=p[pi];}o.wildcard=std::move(r);o.named[x.value]=o.wildcard;return true;}if(pi>=p.size())return false;if(x.kind==detail::segment_kind::exact){if(p[pi]!=x.value)return false;}else o.named[x.value]=std::string(p[pi]);++pi;}return pi==p.size();}
auto router::match(http_method m,std::string_view p)const->std::optional<match_result>{auto parts=detail::split_path(p);auto canonical=detail::canonical_from_parts(parts);if(auto x=find_exact(m,canonical))return match_result{x->handler,{}};const route_entry*best=nullptr;route_params bp;auto consider=[&](std::size_t i){auto&e=entries_[i];route_params x;if(try_match(e.segments,parts,x)&&(!best||detail::better_score(e.score,best->score))){best=&e;bp=std::move(x);}};auto bucket=[&](std::optional<http_method>x,std::string_view first){auto it=first_literal_index_.find(detail::method_bucket_key(x,first));if(it!=first_literal_index_.end())for(auto i:it->second)consider(i);};if(!parts.empty()){bucket(m,parts.front());bucket({},parts.front());}for(auto i:generic_indices_){auto&e=entries_[i];if(!e.method||*e.method==m)consider(i);}if(best)return match_result{best->handler,std::move(bp)};return {};} auto router::match(std::string_view m,std::string_view p)const->std::optional<match_result>{auto x=string_to_method(m);return x?match(*x,p):std::nullopt;}
} // namespace cnetmod::http
