# ==============================================================================
# EmbedMappers.cmake
# Utility function to generate embedded_mappers.hpp from XML mapper files
# ==============================================================================

# Function: cnetmod_embed_mappers
# 
# Generates a C++ header file containing embedded XML mapper content as string literals
#
# Parameters:
#   OUTPUT_FILE   - Path to the generated header file (e.g., ${CMAKE_CURRENT_BINARY_DIR}/embedded_mappers.hpp)
#   MAPPER_DIR    - Directory containing XML mapper files (e.g., ${CMAKE_CURRENT_SOURCE_DIR}/mappers)
#   NAMESPACE     - C++ namespace for the generated code (default: embedded_mappers)
#
# Usage:
#   cnetmod_embed_mappers(
#       OUTPUT_FILE ${CMAKE_CURRENT_BINARY_DIR}/embedded_mappers.hpp
#       MAPPER_DIR ${CMAKE_CURRENT_SOURCE_DIR}/mappers
#       NAMESPACE embedded_mappers
#   )
#
function(cnetmod_embed_mappers)
    # Parse arguments
    set(options "")
    set(oneValueArgs OUTPUT_FILE MAPPER_DIR NAMESPACE)
    set(multiValueArgs "")
    cmake_parse_arguments(EMBED "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    # Validate required arguments
    if(NOT EMBED_OUTPUT_FILE)
        message(FATAL_ERROR "cnetmod_embed_mappers: OUTPUT_FILE is required")
    endif()
    if(NOT EMBED_MAPPER_DIR)
        message(FATAL_ERROR "cnetmod_embed_mappers: MAPPER_DIR is required")
    endif()

    # Set default namespace if not provided
    if(NOT EMBED_NAMESPACE)
        set(EMBED_NAMESPACE "embedded_mappers")
    endif()

    # Find all XML files in the mapper directory
    file(GLOB MAPPER_FILES "${EMBED_MAPPER_DIR}/*.xml")

    # Generate the header file
    file(WRITE ${EMBED_OUTPUT_FILE} "// Auto-generated file - DO NOT EDIT\n")
    file(APPEND ${EMBED_OUTPUT_FILE} "// Generated by cnetmod_embed_mappers() from ${EMBED_MAPPER_DIR}\n")
    file(APPEND ${EMBED_OUTPUT_FILE} "#pragma once\n\n")
    file(APPEND ${EMBED_OUTPUT_FILE} "#include <string_view>\n")
    file(APPEND ${EMBED_OUTPUT_FILE} "#include <flat_map>\n")
    file(APPEND ${EMBED_OUTPUT_FILE} "#include <string>\n\n")
    file(APPEND ${EMBED_OUTPUT_FILE} "namespace ${EMBED_NAMESPACE} {\n\n")

    # For each XML file, create a string literal
    foreach(MAPPER_FILE ${MAPPER_FILES})
        get_filename_component(MAPPER_NAME ${MAPPER_FILE} NAME_WE)

        # Read the XML file content
        file(READ ${MAPPER_FILE} MAPPER_CONTENT)

        # Use C++ raw string literal to avoid escaping issues
        file(APPEND ${EMBED_OUTPUT_FILE} "inline constexpr std::string_view ${MAPPER_NAME} = R\"MAPPER_XML(\n")
        file(APPEND ${EMBED_OUTPUT_FILE} "${MAPPER_CONTENT}")
        file(APPEND ${EMBED_OUTPUT_FILE} ")MAPPER_XML\";\n\n")
    endforeach()

    # Create a function that returns the map
    file(APPEND ${EMBED_OUTPUT_FILE} "inline auto get_all_mappers() -> std::flat_map<std::string, std::string_view> {\n")
    file(APPEND ${EMBED_OUTPUT_FILE} "    std::flat_map<std::string, std::string_view> mappers;\n")
    foreach(MAPPER_FILE ${MAPPER_FILES})
        get_filename_component(MAPPER_NAME ${MAPPER_FILE} NAME_WE)
        file(APPEND ${EMBED_OUTPUT_FILE} "    mappers.insert({\"${MAPPER_NAME}.xml\", ${MAPPER_NAME}});\n")
    endforeach()
    file(APPEND ${EMBED_OUTPUT_FILE} "    return mappers;\n")
    file(APPEND ${EMBED_OUTPUT_FILE} "}\n\n")
    
    # Create a static instance
    file(APPEND ${EMBED_OUTPUT_FILE} "inline const auto all_mappers = get_all_mappers();\n\n")
    file(APPEND ${EMBED_OUTPUT_FILE} "} // namespace ${EMBED_NAMESPACE}\n")

    # Log the result
    list(LENGTH MAPPER_FILES MAPPER_COUNT)
    message(STATUS "Generated ${EMBED_OUTPUT_FILE} with ${MAPPER_COUNT} mapper files")
endfunction()
